### ISSUE TITLE
startCountdown() function don't work in Android

### ISSUE THREAD

**Issue by BF-Myt** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#102]
### Describe your bug here.

I created a custom count down. So I programmed it pretty much like this:

local allowCountDown = false
function onStartCountDown()

      if not allowCountDown then
             allowCountDown = true
             return Function_Stop
      end
end
(This is a example, it wasn't exactly like that)

And when I try to call the function again ( startCountDown() ), the song don't start.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MAJigsaw77** [comment]
I can't fix it, lua broke on original repo
