### ISSUE TITLE
Broken cutscenes

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#103]
### Describe your bug here.

Cutscenes are basically broken like the game just starts the countdown (or ends if an ending cutscene) but plays the song anyway. Same with video's!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No Base Download

**Comment by MAJigsaw77** [comment]
I can't fix it, SM has to do that
