### ISSUE TITLE
Android Controls don't work well

### ISSUE THREAD

**Issue by BF-Myt** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#106]
### Describe your bug here.

When I try to hit 3 notes together, the controller doesn't respond, it only works when I press double note

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MAJigsaw77** [comment]
Huh?
