### ISSUE TITLE
I can't change my control's

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#107]
### Describe your bug here.

I can't change the android controls to hitbox it crashes when trying to enter that state.

### Command Prompt/Terminal logs (if existing)

```bash
android/AndroidControlsSubState.hx (line 119)
flixel/FlxState.hx (line 146)
flixel/FlxState.hx (line 208)
flixel/FlxGame.hx (line 747)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/jigsaw-4277821/FNF-PsychEngine

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No Base Download

**Comment by MAJigsaw77** [comment]
Now you can

**Comment by ImaginationSuperHero528** [comment]
> Now you can 

I understand that this is probably only for quick bug fixes before putting it behind you but all in all this is an awesome port man. Hope you make more awesome stuff!

**Comment by MAJigsaw77** [comment]
Thanks
