### ISSUE TITLE
Song wont start

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#108]
### Describe your bug here.

Idk why but no song will not start no matter the script.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No Base Download

**Comment by ImaginationSuperHero528** [comment]
last commit before something

**Comment by MAJigsaw77** [comment]
Is fixed now
