### ISSUE TITLE
the music starts during the cutscene 

### ISSUE THREAD

**Issue by Luc4s-adv** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#114]
### Describe your bug here.

I put Video Cutscene in a song for a Mod, and while the Cutscene was happening, the Counter/ and the music had already started in the background, while the Cutscene was playing (And before the Cutscene ended the Bf died, since the Cutscene is a bit long), And in another song where the cutscene is just a dialog, after the dialog the controls didn't respond

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Não,apenas a música, vídeo e o .lua para que a Cutscene acontecesse

**Comment by MAJigsaw77** [comment]
I can't fix it dummy
