### ISSUE TITLE
Add a wiki

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#119]
### What needs to be documented?

Why don't you add a wiki and list stuff about the things you've added! For instance I still don't effing understand touchJustPressed. As it just wouldn't work even after you told me how.

**Comment by InsKal** [comment]
wait, are you the one from psych engine server?




Also did u try doing "left" or something like that?

**Comment by ImaginationSuperHero528** [comment]
> wait, are you the one from psych engine server?
> 
> 
> 
> 
> Also did u try doing "left" or something like that?

What? @in

**Comment by MAJigsaw77** [comment]
> ### What needs to be documented?
> Why don't you add a wiki and list stuff about the things you've added! For instance I still don't effing understand touchJustPressed. As it just wouldn't work even after you told me how.

This isn't a office port, you don't need this

**Comment by ImaginationSuperHero528** [comment]
> > ### What needs to be documented?
> > Why don't you add a wiki and list stuff about the things you've added! For instance I still don't effing understand touchJustPressed. As it just wouldn't work even after you told me how.
> 
> This isn't a official port, you don't need this

Why the fucks

**Comment by MAJigsaw77** [comment]
Also, if psych engine is getting Buggy with every update that goes on I'll archive the repo
