### ISSUE TITLE
I Wanna Want Help.

### ISSUE THREAD

**Issue by StefanBETA2008** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#123]
### Describe your problem here.

When I Open The Engine, How Do You Maked This Text:
                                    "Hey, watch out!
             Be careful when you touch the phone fast!
      you can break the phone screen if you do that, also
               this mod contains some flashing lights!
      Press A to disable then now or go to Options Menu.
                       Press B to ignore this message.
                                 You've been warned!"

I Want To Try Porting Something, To Edit This Text, But I Can't Find. Can You Help Me, Saw?

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

Yeah

**Comment by MAJigsaw77** [comment]
This isn't a true issue
