### ISSUE TITLE
Cant pause, die or end song.

### ISSUE THREAD

**Issue by ImaginationSuperHero528** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#124]
### Describe your bug here.

I checked my lua scripts and idk what's wrong!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No Base Download

**Comment by MAJigsaw77** [comment]
.....

**Comment by ImaginationSuperHero528** [comment]
> .....

- Ik this is probably something on my but I legit removed all scripts! Can you at least check the code for Function_Continue and stuff?

**Comment by ImaginationSuperHero528** [comment]
Oh and if there's a cutscene the song doesn't start.

**Comment by ImaginationSuperHero528** [comment]
It was a scriot
