### ISSUE TITLE
Mod songs don't work

### ISSUE THREAD

**Issue by FatFootballer21** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#126]
### Describe your bug here.

The mod songs never start and you can't exit them unless you exit the game

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No, Base Download

**Comment by MAJigsaw77** [comment]
That happens because of your phone performance

**Comment by FatFootballer21** [comment]
It's actually the countdown that never starts, plus my phone has 6 GB of RAM
