### ISSUE TITLE
startCountDown() function don't work again

### ISSUE THREAD

**Issue by BF-Myt** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#127]
### Describe your bug here.

By the looks of it, until a few weeks ago some mods were starting the songs normally. But when this update came, half of the mods don't start the songs with startCountDown() function.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by MAJigsaw77** [comment]
O can't fix it, psych got bugged
