### ISSUE TITLE
The Sutil.hx Missing 

### ISSUE THREAD

**Issue by StefanBETA2008** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#141]
### Describe your bug here.

How To Fix This? 
![Screenshot_20220804-214347~2](https://user-images.githubusercontent.com/109828559/182939266-e5f02a52-c252-4091-a90b-12bb38b2e9f8.png)

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

I Wanna Want Make My Engine Damn :(

**Comment by mcagabe19** [comment]
BRU- just remove ###import android.PermissionsList from SUtill

**Comment by StefanBETA2008** [comment]
> 

We'll, I Just Remove, And Again, Error

**Comment by mcagabe19** [comment]
screenshot?

**Comment by StefanBETA2008** [comment]
> screenshot?

Wait, I Need Screenshot First

**Comment by mcagabe19** [comment]
> Wait, I Need Screenshot First

ok

**Comment by StefanBETA2008** [comment]
Bro, You Are The Great. It's Work

**Comment by mcagabe19** [comment]
> Bro, You Are The Great. It's Work

Thats Right Bcuz I Porting Vs Steve On Android And I Getted Same Issue

**Comment by StefanBETA2008** [comment]
Okay, Cool. But I Don't See The Problem Before. What Happened?

**Comment by mcagabe19** [comment]
> Okay, Cool, But I Don't See The Problem Before. What Happened?

Jigsaw updated Android Tools

**Comment by StefanBETA2008** [comment]
Damn, That So Sad. Why? It's For The Update Or Something
