### ISSUE TITLE
Dialouge starts after countdown

### ISSUE THREAD

**Issue by Kaixvny** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#92]
### Describe your problem here.

trying to get dialouge to load but it always starts after the countdown which means it plays while song is playing

```
local allowCountdown = false
function onStartCountdown()
	-- Block the first countdown and start a timer of 0.8 seconds to play the dialogue
	if not allowCountdown and isStoryMode and not seenCutscene then
		setProperty('inCutscene', true);
		runTimer('startDialogue', 0.8);
		allowCountdown = true;
		return Function_Stop;
	end
	return Function_Continue;
end

function onTimerCompleted(tag, loops, loopsLeft)
	if tag == 'startDialogue' then -- Timer completed, play dialogue
		startDialogue('dialogue', 'breakfast');
	end
end 
```

thats the code im using in a lua script file in the data folder.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

 a few things, nothing major in the code that i think could cause this (postion of a few menu items, and added stages and achievements)

**Comment by SMVDHFEYF** [comment]
Same with me:(

**Comment by D3MONSLAY3R101** [comment]
I am having this problem too.

**Comment by mcagabe19** [comment]
this is jigsaw's mistake you needed install latest version

**Comment by mcagabe19** [comment]
but you can fork and can make your psych

**Comment by mcagabe19** [comment]
you have discord?

**Comment by NocontextMomemt** [comment]
The dude your Questioning is ThatUserwhois
