### ISSUE TITLE
Softlock with some mods

### ISSUE THREAD

**Issue by IceStar2** [MAJigsaw77/FNF-PsychEngine-With-Android-Support#99]
### Describe your bug here.

When I try to play a mod (for exemple the whitty mod), the game sometimes softlock during the camera mouvement at the start of the song and then nothing else happen (no 3, 2, 1, go ; no music ; no arrows (even the gray ones) ; sometimes no animation with the character)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

I just added some mods in the mods folder

**Comment by Sussysnowman** [comment]
Yea same thing happends to me when i try to play indie cross port bruh

**Comment by Sussysnowman** [comment]
Ok looks like most mods for the old version of pe are broken mega rip☠

**Comment by IceStar2** [comment]
Yea

**Comment by MAJigsaw77** [comment]
This is just need nonsensical
